### ISSUE TITLE
Syntax error in vm.js (csso-cli v4.0)

### ISSUE THREAD

**Issue by Orajo** [css/csso-cli#28]
Calling csso-cli from command line I got this error. Downgrade to 3.0.0 fix the poroblem
(function (exports, require, module, __filename, __dirname) { import { basename, extname } from 'path';
                                                                                                      ^

SyntaxError: Unexpected token {
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:696:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by lahmatiy** [comment]
Not enough details to understand what the problem is. What version of nodejs are you using?

**Comment by jyotir07** [comment]
You might just be missing a semi-colon(;)       
But js automatically adds this in the end of the line so it can be something else too
