### ISSUE TITLE
this.showHelp is not a function

### ISSUE THREAD

**Issue by kkmuffme** [css/csso-cli#29]
Command I ran:
>node_modules/.bin/csso

Error:

```
node_modules/.bin/csso
/my-dir/node_modules/csso-cli/bin/csso:15
    throw e;
    ^

TypeError: this.showHelp is not a function
    at /my-dir/node_modules/csso-cli/lib/index.js:329:18
    at Command.run (/my-dir/node_modules/clap/cjs/command.cjs:174:33)
    at Object.run (/my-dir/node_modules/csso-cli/lib/index.js:346:30)
    at Object.<anonymous> (/my-dir/node_modules/csso-cli/bin/csso:6:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by lahmatiy** [comment]
Fixed in [4.0.2](https://github.com/css/csso-cli/releases/tag/v4.0.2)
